from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import fnmatch
import re
import shlex
import subprocess
import tomllib

from .git import ChangedFile, CommitInfo, Numstat


BLOCKER = "BLOCKER"
WARNING = "WARNING"
INFO = "INFO"


RULE_DOC_NAMES = (
    "CONTRIBUTING",
    "CONTRIBUTING.md",
    "CONTRIBUTING.rst",
    "DEVELOPING.md",
    "DEVELOPMENT.md",
    "MAINTAINERS",
    "MAINTAINERS.md",
    "SECURITY.md",
    "CODE_OF_CONDUCT.md",
    "LICENSE",
    "LICENSE.md",
    "COPYING",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/pull_request_template.md",
)

MONOREPO_RULE_DOC_NAMES = {"CONTRIBUTING.md", "DEVELOPING.md", "DEVELOPMENT.md"}

GENERATED_PARTS = {
    "dist",
    "build",
    "coverage",
    "node_modules",
    ".next",
    ".nuxt",
    "target",
    "out",
    "generated",
    "gen",
}

VENDOR_PARTS = {"vendor", "vendors", "third_party", "third-party", "external"}

SOURCE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".mjs",
    ".php",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".sh",
    ".swift",
    ".ts",
    ".tsx",
}

TEST_PARTS = {"test", "tests", "spec", "specs", "__tests__"}

AI_MARKERS = re.compile(
    r"(?i)(as an ai|chatgpt|claude|copilot|generated by ai|ai-generated|ai generated|"
    r"vibe[- ]?cod|ai slop|large language model|llm-generated|prompted by)"
)

PLACEHOLDERS = re.compile(
    r"(?i)\b(todo|fixme|xxx|hack|temporary|placeholder|stub|not implemented|for now|"
    r"good enough|probably works|needs cleanup|follow-up)\b"
)

SECRET_PATTERNS = (
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"(?i)-----BEGIN (RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][^'\"]{16,}['\"]"),
)

WEAK_SECTION_TEXT = re.compile(
    r"(?is)^\s*(n/?a|none|no|unknown|todo|tbd|not sure|state whether|fill this|placeholder|used|yes)\s*\.?\s*$"
)

ACCOUNTABILITY_WORDS = re.compile(r"(?i)\b(responsib|accountab|own|reviewed|verified|tested|license|security|every line)\b")

PASSING_EVIDENCE = re.compile(
    r"(?is)\b(pass(?:ed)?|success(?:ful)?|ok|green|clean|exit\s*0|0\s*failures?|ci\s+passed)\b"
)

CHECK_COMMAND_EVIDENCE = re.compile(
    r"(?is)(`[^`]+`|\b(nix\s+flake\s+check|pytest|python\s+-m\s+unittest|unittest|cargo\s+test|go\s+test|"
    r"npm\s+test|yarn\s+test|pnpm\s+test|make\s+test|mvn\s+test|gradle\s+test|dotnet\s+test|ci)\b)"
)


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    file: str | None = None
    detail: str | None = None


@dataclass(frozen=True)
class CheckResult:
    command: str
    returncode: int
    output: str


@dataclass
class PolicyConfig:
    max_changed_files: int = 25
    max_added_lines: int = 800
    max_deleted_lines: int = 500
    max_file_added_lines: int = 300
    require_upstream_rules: bool = True
    require_tests_for_code: bool = True
    require_test_changes_for_code: bool = True
    block_generated_paths: bool = True
    block_vendor_paths: bool = True
    block_ai_markers: bool = True
    block_placeholders: bool = True
    allow_paths: list[str] = field(default_factory=list)
    required_checks: list[str] = field(default_factory=list)

    @classmethod
    def load(cls, repo: Path) -> "PolicyConfig":
        path = repo / ".themis.toml"
        if not path.exists():
            return cls()
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        allowed = {field.name for field in cls.__dataclass_fields__.values()}  # type: ignore[attr-defined]
        known_tables = {"policy", "ai"}
        unknown_top_level = sorted(set(data) - allowed - known_tables)
        if unknown_top_level:
            raise ValueError(f"unknown top-level keys in {path}: {', '.join(unknown_top_level)}")
        top_level_policy_keys = sorted(set(data) & allowed)
        if "policy" in data and top_level_policy_keys:
            raise ValueError(f"policy keys must not be mixed with [policy] in {path}: {', '.join(top_level_policy_keys)}")
        policy = data.get("policy", {key: value for key, value in data.items() if key in allowed})
        unknown = sorted(set(policy) - allowed)
        if unknown:
            raise ValueError(f"unknown policy keys in {path}: {', '.join(unknown)}")
        return cls(**policy)


@dataclass(frozen=True)
class ValidationInput:
    repo: Path
    base: str | None
    changed_files: list[ChangedFile]
    numstat: list[Numstat]
    diff_text: str
    tracked_files: list[str]
    commits: list[CommitInfo]
    pr_description: str
    test_evidence: str
    ai_assisted: bool
    check_results: list[CheckResult]


def validate(data: ValidationInput, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    rule_docs = load_rule_docs(data.repo)
    docs_text = "\n".join(content for _, content in rule_docs)

    findings.extend(validate_scope(data, config))
    findings.extend(validate_upstream_rules(rule_docs, data, docs_text, config))
    findings.extend(validate_project_specific_rules(rule_docs, data, docs_text))
    findings.extend(validate_ai_disclosure(data, docs_text))
    findings.extend(validate_paths(data, config))
    findings.extend(validate_diff_content(data, config))
    findings.extend(validate_tests(data, docs_text, config))
    findings.extend(validate_checks(data, config))

    if not any(item.severity == BLOCKER for item in findings):
        findings.append(
            Finding(
                INFO,
                "clean-static-gate",
                "No hard blockers were found by configured static checks. This is not a guarantee of correctness or upstream acceptance.",
            )
        )
    return findings


def validate_project_specific_rules(
    rule_docs: list[tuple[str, str]],
    data: ValidationInput,
    docs_text: str,
) -> list[Finding]:
    findings: list[Finding] = []
    pr_text = data.pr_description.lower()
    code_changes = [item.path for item in data.changed_files if is_source_path(item.path) and not is_test_path(item.path)]
    process_text = "\n".join(content for name, content in rule_docs if is_process_rule_doc(name))

    for name, content in rule_docs:
        if "pull_request_template" not in name.lower():
            continue
        required_boxes = [line.strip() for line in content.splitlines() if re.match(r"[-*]\s+\[\s*\]", line.strip())]
        if required_boxes and "[x]" not in pr_text and "[X]" not in data.pr_description:
            findings.append(
                Finding(
                    BLOCKER,
                    "pr-template-not-acknowledged",
                    "Upstream PR template contains checklist items, but the PR description does not show checked acknowledgements.",
                    file=name,
                )
            )

    if code_changes and docs_require_changelog(process_text):
        has_changelog_change = any(re.search(r"(?i)(change.?log|changes|release.?notes|news)", item.path) for item in data.changed_files)
        has_changelog_note = re.search(r"(?im)^\s*(change.?log|release notes?)\s*:\s*(not needed|n/a|none|yes|updated)", data.pr_description)
        if not has_changelog_change and not has_changelog_note:
            findings.append(
                Finding(
                    BLOCKER,
                    "missing-changelog-decision",
                    "Upstream docs appear to require changelog/release-note handling, but no changelog file or explicit PR decision was found.",
                )
            )

    if docs_require_issue_link(process_text) and not re.search(r"(?i)(fixes|closes|refs|references)\s+#\d+|https?://\S+/(issues|pull)/\d+", data.pr_description):
        findings.append(
            Finding(
                BLOCKER,
                "missing-issue-link",
                "Upstream docs appear to require an issue/reference link, but the PR description does not include one.",
            )
        )

    if docs_require_conventional_commits(process_text):
        if not data.base:
            findings.append(Finding(BLOCKER, "cannot-verify-commit-style", "Upstream docs require conventional commits, but no base ref was provided."))
        elif not data.commits:
            findings.append(Finding(BLOCKER, "cannot-verify-commit-style", "Upstream docs require conventional commits, but no commits were found in the base range."))
        else:
            invalid = [commit for commit in data.commits if not commit.is_merge and not is_conventional_commit(commit.subject)]
            if invalid:
                detail = ", ".join(f"{commit.sha[:12]} {commit.subject}" for commit in invalid)
                findings.append(Finding(BLOCKER, "invalid-commit-style", "Upstream docs appear to require conventional commits.", detail=trim(detail, 500)))

    return findings


def load_rule_docs(repo: Path) -> list[tuple[str, str]]:
    docs: list[tuple[str, str]] = []
    candidates = set(RULE_DOC_NAMES)
    github = repo / ".github"
    if github.exists():
        for path in github.rglob("*.md"):
            if "ISSUE_TEMPLATE" in path.parts:
                continue
            candidates.add(str(path.relative_to(repo)))
    for path in repo.rglob("*.md"):
        relative = str(path.relative_to(repo))
        if path.name not in MONOREPO_RULE_DOC_NAMES:
            continue
        if set(path.relative_to(repo).parts) & (GENERATED_PARTS | VENDOR_PARTS | {".git"}):
            continue
        candidates.add(relative)
    for name in sorted(candidates):
        path = repo / name
        if path.is_file():
            try:
                docs.append((name, path.read_text(encoding="utf-8", errors="replace")))
            except OSError:
                continue
    return docs


def validate_scope(data: ValidationInput, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    changed_by_path = {item.path: item for item in data.changed_files}
    if not data.changed_files:
        findings.append(Finding(BLOCKER, "no-changes", "No changes were found to validate."))
        return findings
    if len(data.changed_files) > config.max_changed_files:
        findings.append(
            Finding(
                BLOCKER,
                "too-many-files",
                f"Patch changes {len(data.changed_files)} files; maximum is {config.max_changed_files}.",
            )
        )

    total_added = sum(item.added or 0 for item in data.numstat)
    total_deleted = sum(item.deleted or 0 for item in data.numstat)
    if total_added > config.max_added_lines:
        findings.append(Finding(BLOCKER, "too-many-additions", f"Patch adds {total_added} lines; maximum is {config.max_added_lines}."))
    if total_deleted > config.max_deleted_lines:
        findings.append(Finding(BLOCKER, "too-many-deletions", f"Patch deletes {total_deleted} lines; maximum is {config.max_deleted_lines}."))
    for item in data.numstat:
        if item.added is not None and item.added > config.max_file_added_lines:
            findings.append(
                Finding(BLOCKER, "file-too-large", f"File adds {item.added} lines; maximum is {config.max_file_added_lines}.", file=item.path)
            )
        changed = changed_by_path.get(item.path)
        if (item.added is None or item.deleted is None) and not (changed and changed.status.startswith("D")):
            findings.append(Finding(BLOCKER, "binary-change", "Binary file changes require explicit maintainer review.", file=item.path))
    return findings


def validate_upstream_rules(
    rule_docs: list[tuple[str, str]],
    data: ValidationInput,
    docs_text: str,
    config: PolicyConfig,
) -> list[Finding]:
    findings: list[Finding] = []
    if config.require_upstream_rules and not rule_docs:
        findings.append(
            Finding(
                BLOCKER,
                "missing-upstream-rules",
                "No upstream contribution/rules documents were found; fail closed instead of guessing maintainer requirements.",
            )
        )
    if docs_require_dco_or_signoff(docs_text):
        unsigned = [
            commit
            for commit in data.commits
            if not commit.is_merge and "Signed-off-by:" not in f"{commit.subject}\n{commit.body}"
        ]
        if data.base and data.changed_files and not data.commits:
            findings.append(Finding(BLOCKER, "cannot-verify-dco", "Upstream docs mention DCO/signoff, but no commits were found in the base range."))
        elif data.base and unsigned:
            detail = ", ".join(commit.sha[:12] for commit in unsigned)
            findings.append(Finding(BLOCKER, "missing-signed-off-by", "Upstream docs mention DCO/signoff, but commits are missing Signed-off-by trailers.", detail=detail))
        elif not data.base:
            findings.append(Finding(BLOCKER, "cannot-verify-dco", "Upstream docs mention DCO/signoff, but no base ref was provided to inspect commits."))
    return findings


def validate_ai_disclosure(data: ValidationInput, docs_text: str) -> list[Finding]:
    findings: list[Finding] = []
    forbid_ai = docs_forbid_ai(docs_text)
    require_ai_disclosure = re.search(r"(?is)\b(ai|llm|generative|generated).{0,120}\b(disclos|indicat|mention|declare)", docs_text)
    if data.ai_assisted and forbid_ai:
        findings.append(Finding(BLOCKER, "upstream-forbids-ai", "Upstream docs appear to forbid AI-generated/AI-assisted contributions."))
    if data.ai_assisted:
        description = data.pr_description.lower()
        if "ai assistance:" not in description:
            findings.append(Finding(BLOCKER, "missing-ai-disclosure", "AI-assisted submissions must include an `AI assistance:` section in the PR description."))
        else:
            ai_section = extract_labeled_section(data.pr_description, "AI assistance")
            if weak_section(ai_section):
                findings.append(Finding(BLOCKER, "weak-ai-disclosure", "`AI assistance:` must explain how AI was used and how the output was reviewed."))
        if "human accountability:" not in description:
            findings.append(Finding(BLOCKER, "missing-human-accountability", "AI-assisted submissions must include a `Human accountability:` responsibility statement."))
        else:
            accountability = extract_labeled_section(data.pr_description, "Human accountability")
            if weak_section(accountability) or not ACCOUNTABILITY_WORDS.search(accountability):
                findings.append(Finding(BLOCKER, "weak-human-accountability", "`Human accountability:` must explicitly state that the submitter takes responsibility for the submitted work."))
    if require_ai_disclosure and not data.ai_assisted:
        findings.append(
            Finding(
                WARNING,
                "upstream-ai-policy-present",
                "Upstream docs mention AI disclosure; ensure `--human-authored` is accurate or provide AI disclosure.",
            )
        )
    return findings


def validate_paths(data: ValidationInput, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    for changed in data.changed_files:
        if path_allowed(changed.path, config.allow_paths):
            continue
        parts = set(Path(changed.path).parts)
        name = Path(changed.path).name.lower()
        if config.block_generated_paths and (parts & GENERATED_PARTS or name.endswith((".min.js", ".min.css", ".map"))):
            findings.append(Finding(BLOCKER, "generated-path", "Generated/build/minified output is blocked unless explicitly allowed.", file=changed.path))
        if config.block_vendor_paths and parts & VENDOR_PARTS:
            findings.append(Finding(BLOCKER, "vendor-path", "Vendored/third-party changes are blocked unless explicitly allowed.", file=changed.path))
        if changed.status.startswith("D") and is_test_path(changed.path):
            findings.append(Finding(BLOCKER, "deleted-test", "Deleting tests is a hard blocker without explicit maintainer direction.", file=changed.path))
    return findings


def validate_diff_content(data: ValidationInput, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    current_file: str | None = None
    for line in data.diff_text.splitlines():
        if line.startswith("+++ b/"):
            current_file = line.removeprefix("+++ b/")
            continue
        if not line.startswith("+") or line.startswith("+++"):
            continue
        added = line[1:]
        if not added.strip():
            continue
        if config.block_ai_markers and AI_MARKERS.search(added) and should_block_ai_marker(current_file, added):
            findings.append(Finding(BLOCKER, "ai-marker-in-diff", "Added line contains AI-tool/slop marker text.", file=current_file, detail=trim(added)))
        if config.block_placeholders and PLACEHOLDERS.search(added) and should_block_placeholder(current_file, added):
            findings.append(Finding(BLOCKER, "placeholder-in-code", "Added code contains placeholder or cleanup language.", file=current_file, detail=trim(added)))
        for pattern in SECRET_PATTERNS:
            if pattern.search(added):
                findings.append(Finding(BLOCKER, "secret-looking-value", "Added line looks like a secret or credential.", file=current_file))
        if re.search(r"(?i)\b(debugger|console\.log|print\(.{0,80}debug|pdb\.set_trace)\b", added) and not is_test_path(current_file or ""):
            findings.append(Finding(BLOCKER, "debug-leftover", "Added code appears to contain debugging leftovers.", file=current_file, detail=trim(added)))
        if re.search(r"\bexcept\s+Exception\s*:\s*(pass)?\s*$", added):
            findings.append(Finding(BLOCKER, "swallowed-exception", "Broad swallowed exceptions are blocked.", file=current_file, detail=trim(added)))
    return dedupe(findings)


def validate_tests(data: ValidationInput, docs_text: str, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    code_changes = [item.path for item in data.changed_files if is_source_path(item.path) and not is_test_path(item.path)]
    test_changes = [item.path for item in data.changed_files if is_test_path(item.path)]
    docs_mention_tests = re.search(r"(?i)\b(test|tests|tested|pytest|unit test|integration test|ci)\b", docs_text)

    if not code_changes:
        return findings
    if config.require_tests_for_code and not data.test_evidence.strip() and not any(result.returncode == 0 for result in data.check_results):
        findings.append(Finding(BLOCKER, "missing-test-evidence", "Code changed, but no test evidence or successful required check was provided."))
    elif config.require_tests_for_code and data.test_evidence.strip() and not strong_test_evidence(data.test_evidence):
        findings.append(Finding(BLOCKER, "weak-test-evidence", "Test evidence must name a check/command or CI run and state that it passed."))
    if config.require_test_changes_for_code and not test_changes:
        findings.append(Finding(BLOCKER, "missing-test-changes", "Code changed, but no test files changed. Provide tests or configure an explicit exception."))
    if docs_mention_tests and not data.test_evidence.strip() and not any(result.returncode == 0 for result in data.check_results):
        findings.append(Finding(BLOCKER, "upstream-tests-not-proven", "Upstream docs mention testing, but this validation run has no passing test evidence."))
    return findings


def validate_checks(data: ValidationInput, config: PolicyConfig) -> list[Finding]:
    findings: list[Finding] = []
    if config.required_checks and not data.check_results:
        findings.append(Finding(BLOCKER, "required-checks-not-run", "Policy defines required checks, but they were not run. Use `themis validate --run-checks` or `themis pull-request draft`."))
        return findings
    for result in data.check_results:
        if result.returncode != 0:
            findings.append(Finding(BLOCKER, "required-check-failed", f"Required check failed: `{result.command}`", detail=trim(result.output, 500)))
    return findings


def run_required_checks(repo: Path, commands: list[str]) -> list[CheckResult]:
    results: list[CheckResult] = []
    for command in commands:
        args = shlex.split(command)
        if not args:
            continue
        completed = subprocess.run(
            args,
            cwd=repo,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        results.append(CheckResult(command=command, returncode=completed.returncode, output=completed.stdout))
    return results


def path_allowed(path: str, allowed: list[str]) -> bool:
    return any(path.startswith(item.rstrip("/") + "/") or fnmatch.fnmatch(path, item) for item in allowed)


def is_source_path(path: str) -> bool:
    return Path(path).suffix.lower() in SOURCE_EXTENSIONS


def is_test_path(path: str) -> bool:
    lowered = path.lower()
    parts = set(Path(lowered).parts)
    name = Path(lowered).name
    return bool(parts & TEST_PARTS) or name.startswith("test_") or name.endswith(("_test.py", ".test.js", ".spec.js", ".test.ts", ".spec.ts"))


def is_low_risk_text_file(path: str | None) -> bool:
    if not path:
        return False
    suffix = Path(path).suffix.lower()
    return suffix in {".md", ".rst", ".txt"}


def is_process_rule_doc(name: str) -> bool:
    normalized = name.lower()
    excluded = ("code_of_conduct", "security", "license", "copying", "issue_template")
    return not any(part in normalized for part in excluded)


def should_block_placeholder(path: str | None, line: str) -> bool:
    if is_low_risk_text_file(path) or is_test_path(path or ""):
        return False
    if "re.compile(" in line or "FindingExplanation(" in line:
        return False
    if is_string_literal_line(line):
        return False
    return True


def should_block_ai_marker(path: str | None, line: str) -> bool:
    if is_low_risk_text_file(path) or is_test_path(path or ""):
        return False
    if "re.compile(" in line or is_string_literal_line(line):
        return False
    return True


def is_string_literal_line(line: str) -> bool:
    stripped = line.lstrip()
    return stripped.startswith(("\"", "'", "r\"", "r'", "f\"", "f'"))


def extract_labeled_section(text: str, label: str) -> str:
    pattern = re.compile(rf"(?ims)^\s*{re.escape(label)}\s*:\s*(.*?)(?=^\s*[A-Z][A-Za-z /-]{{2,40}}\s*:|\Z)")
    match = pattern.search(text)
    if not match:
        return ""
    return match.group(1).strip()


def weak_section(value: str) -> bool:
    return not value.strip() or bool(WEAK_SECTION_TEXT.match(value.strip()))


def strong_test_evidence(value: str) -> bool:
    return bool(PASSING_EVIDENCE.search(value) and CHECK_COMMAND_EVIDENCE.search(value))


def docs_require_changelog(text: str) -> bool:
    return bool(
        re.search(
            r"(?is)\b(must|required|require|should|need to|include|add|update).{0,80}\b(change.?log|release[ -]?notes|news)",
            text,
        )
        or re.search(
            r"(?is)\b(need|needs|include|add|update).{0,80}\brelease\s+notes\b",
            text,
        )
    )


def docs_require_dco_or_signoff(text: str) -> bool:
    return bool(re.search(r"(?i)\b(dco|signed-off-by|sign[ -]?off|developer certificate of origin)\b", text))


def docs_require_issue_link(text: str) -> bool:
    return bool(
        re.search(
            r"(?is)\b(pull request|pr|change|patch|contribution|commit).{0,120}\b(must|required|require|should|need to).{0,120}\b(issue|ticket|bug report|reference|fixes|closes)",
            text,
        )
        or re.search(
            r"(?is)\b(must|required|require|should|need to).{0,120}\b(issue|ticket|bug report|reference|fixes|closes).{0,120}\b(pull request|pr|change|patch|contribution|commit)",
            text,
        )
        or re.search(
            r"(?is)\b(reference|link|fixes|closes).{0,80}\b(issue|ticket|bug report)",
            text,
        )
        or re.search(
            r"(?is)\b(issue|ticket|bug report).{0,80}\b(fixes|closes|references|links?)",
            text,
        )
    )


def docs_require_conventional_commits(text: str) -> bool:
    return bool(
        re.search(r"(?is)\b(conventional commits?|commit message).{0,100}\b(feat|fix|docs|chore|type|scope)", text)
        or re.search(r"(?is)\b(must|required|require|should|need to|follow|use).{0,80}\bconventional commits?\b", text)
    )


def docs_forbid_ai(text: str) -> bool:
    return any(
        re.search(pattern, text)
        for pattern in (
            r"(?is)\b(ai|llm|chatgpt|generative ai|ai-generated|ai generated|llm-generated).{0,80}\b(contributions?|code|patch(?:es)?|pull requests?).{0,80}\b(not accepted|forbidden|prohibited|rejected|disallowed)",
            r"(?is)\b(do not|must not|cannot|may not|never).{0,40}\b(submit|contribute|include|use).{0,80}\b(ai|llm|chatgpt|generative ai|ai-generated|ai generated|llm-generated)",
            r"(?is)\b(no|forbidden|prohibited|reject(?:s|ed)?|not accepted).{0,40}\b(ai-generated|ai generated|llm-generated|generative ai).{0,40}\b(code|contributions?|patch(?:es)?|pull requests?)",
        )
    )


def is_conventional_commit(subject: str) -> bool:
    return bool(re.match(r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?!?: .+", subject))


def trim(value: str, limit: int = 180) -> str:
    value = value.strip()
    if len(value) <= limit:
        return value
    return value[: limit - 3] + "..."


def dedupe(findings: list[Finding]) -> list[Finding]:
    seen: set[tuple[str, str | None, str | None]] = set()
    unique: list[Finding] = []
    for finding in findings:
        key = (finding.code, finding.file, finding.detail)
        if key in seen:
            continue
        seen.add(key)
        unique.append(finding)
    return unique
